/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import Excepcion.DocumentoDuplicadoException;
import Excepcion.documentoNoExisteExeption;
import Modelo.Estudiante;
import Util.Lista;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Vista extends javax.swing.JFrame {

    private Controlador controlador;
    private DefaultTableModel modeloTablaEstudiante;

    public Vista() {
        initComponents();
        setLocationRelativeTo(this);
        controlador = new Controlador();
        modeloTablaEstudiante = new DefaultTableModel();
       mostrarEstudiatesenTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreAcudiente = new javax.swing.JLabel();
        lblNumeroAcudiente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreEstudiante = new javax.swing.JTextField();
        txtDocumentoEstudiante = new javax.swing.JTextField();
        txtNumeroDecurso = new javax.swing.JTextField();
        txtEdadEstudiante = new javax.swing.JTextField();
        txtNombreAcudiente = new javax.swing.JTextField();
        txtNumeroAcudiente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre Estudiante:");

        lblNombreAcudiente.setText("Nombre Acudiente:");

        lblNumeroAcudiente.setText("Numero Acudiente:");

        jLabel2.setText("Numero de curso:");

        jLabel3.setText("Edad estudiante");

        jLabel4.setText("documento estudiante:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEstudiantes);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroDecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumeroAcudiente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditar)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNumeroAcudiente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDocumentoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombreAcudiente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(txtEdadEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(428, Short.MAX_VALUE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(txtNombreAcudiente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDocumentoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumeroDecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEdadEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAcudiente)
                    .addComponent(txtNombreAcudiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroAcudiente)
                    .addComponent(txtNumeroAcudiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnBuscar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        boolean validacion = validarCamposVacios();
        if (validacion) {
            JOptionPane.showMessageDialog(null, "Por favor llenar todos los campos de formulario del estudiante. "
                    + "\n gracias");
        } else {
            String nombreEstudiante = txtNombreEstudiante.getText();
            String docuementoEstudiante = txtDocumentoEstudiante.getText();
            int numeroDeCurso = Integer.parseInt(txtNumeroDecurso.getText());
            int edadEstudiante = Integer.parseInt(txtEdadEstudiante.getText());
            String nombreAcudiente = txtNombreAcudiente.getText();
            String numeroAcudiente = txtNumeroAcudiente.getText();

            Estudiante estudiante = new Estudiante(nombreEstudiante, docuementoEstudiante, numeroDeCurso, edadEstudiante, nombreAcudiente, numeroAcudiente);
            try {
                controlador.registrarEstudiante(estudiante);

                JOptionPane.showMessageDialog(null, " el estudiante se registro correctamente con la Cedula  " + docuementoEstudiante);
                limpiarCampos();
                mostrarEstudiatesenTabla();

            } catch (DocumentoDuplicadoException docuementoDuplicadoException) {
                JOptionPane.showMessageDialog(null, docuementoDuplicadoException.getMessage());

            }

        }


    }//GEN-LAST:event_btnAgregarActionPerformed


    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        String documento = txtDocumentoEstudiante.getText();
        Estudiante auxiliar = controlador.buscarEstudiante(documento);
        if (auxiliar != null) {
            txtNombreEstudiante.setText(auxiliar.getNombre());
            txtDocumentoEstudiante.setText(auxiliar.getDocumento());
            txtEdadEstudiante.setText(String.valueOf(auxiliar.getEdad()));
            txtNumeroDecurso.setText(String.valueOf(auxiliar.getNumeroDecurso()));
            txtNombreAcudiente.setText(auxiliar.getNombreAcudiente());
            txtNumeroAcudiente.setText(auxiliar.getNumeroAcudiente());

        } else {
            JOptionPane.showMessageDialog(null, "El estudiante bajo este numero de documento  " + documento + "  NO existe ");
            txtDocumentoEstudiante.setText("");
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (validarCamposVacios()) {
            JOptionPane.showMessageDialog(null, " por favor recuerde COMPLETAR todos los datos del estudiante al editar ");
        } else {

            String nombreEstudiante = txtNombreEstudiante.getText();
            String documentoEstudiante = txtDocumentoEstudiante.getText();
            int EdadEstudiante = Integer.parseInt(txtEdadEstudiante.getText());
            int numeroDeCurso = Integer.parseInt(txtNumeroDecurso.getText());
            String nombreAcudiente = txtNombreAcudiente.getText();
            String numeroAcudiente = txtNumeroAcudiente.getText();

            Estudiante auxiliarEst = new Estudiante(nombreEstudiante, documentoEstudiante, EdadEstudiante, numeroDeCurso, nombreAcudiente, numeroAcudiente);
            try {
                controlador.editarEstu(auxiliarEst);
                JOptionPane.showMessageDialog(null, " Se edito CORRECTAMENTE el estudiante con documento " + documentoEstudiante);
                limpiarCampos();
                mostrarEstudiatesenTabla();

            } catch (documentoNoExisteExeption documentoNoExisteExeption1) {
                JOptionPane.showMessageDialog(null, documentoNoExisteExeption1.getMessage());

            }

        }


    }//GEN-LAST:event_btnEditarActionPerformed

    public void mostrarEstudiatesenTabla() {
        String[][] tablaAlumnos = new String[controlador.getLista().size()][6];
        for (int i = 0; i < controlador.getLista().size(); i++) {
            tablaAlumnos[i][0] = controlador.estudiante(i).getNombre();
            tablaAlumnos[i][1] = controlador.estudiante(i).getDocumento();
            tablaAlumnos[i][2]= String.valueOf(controlador.estudiante(i).getNumeroDecurso());
            tablaAlumnos[i][3] = String.valueOf(controlador.estudiante(i).getEdad());  // todo lo que sea int lo ingreso aca Strign valu uf
            tablaAlumnos[i][4] = controlador.estudiante(i).getNombreAcudiente();
            tablaAlumnos[i][5] = controlador.estudiante(i).getNumeroAcudiente();
           
             }
        
        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
                tablaAlumnos,
                new String[]{
                    "Nombre", "Documento", "Numero De Salon", "Edad","Nombre Acudiente","Numero Acudiente"
                }
        ));

    }

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (validarCamposBuscarYEliminar()) {
            JOptionPane.showMessageDialog(null, " Recuerda ingresar el documento del estudiante ");
        } else {

            String documento = txtDocumentoEstudiante.getText();
            boolean respuesta = controlador.eliminarEstudiante(documento);
            if (respuesta) {
                JOptionPane.showMessageDialog(null, " se elimino CORRECTAMENTE el estudiante con documento    " + documento);
                limpiarCampos();
                mostrarEstudiatesenTabla();
            } else {
                JOptionPane.showMessageDialog(null, " NO se elimino  el estudiante con documento    " + documento);
            }

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreAcudiente;
    private javax.swing.JLabel lblNumeroAcudiente;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaEstudiantes;
    private javax.swing.JTextField txtDocumentoEstudiante;
    private javax.swing.JTextField txtEdadEstudiante;
    private javax.swing.JTextField txtNombreAcudiente;
    private javax.swing.JTextField txtNombreEstudiante;
    private javax.swing.JTextField txtNumeroAcudiente;
    private javax.swing.JTextField txtNumeroDecurso;
    // End of variables declaration//GEN-END:variables

    private boolean validarCamposVacios() {

        String nombreEstudiante = txtNombreEstudiante.getText();
        String docuementoEstudiante = txtDocumentoEstudiante.getText();
        String numeroDeCurso = txtNumeroDecurso.getText();  //
        String edadEstudiante = txtEdadEstudiante.getText(); //
        String nombreAcudiente = txtNombreAcudiente.getText();
        String numeroAcudiente = txtNumeroAcudiente.getText();

        if (nombreEstudiante.isBlank() || docuementoEstudiante.isBlank() || numeroDeCurso.isBlank() || edadEstudiante.isBlank() || nombreAcudiente.isBlank() || numeroAcudiente.isBlank()) {
            return true;
        } else {
            int numeroCurso = Integer.parseInt(numeroDeCurso);
            int edadEstu = Integer.parseInt(edadEstudiante);
            return false;
        }
    }

    /*
    metodo para limpiar los campos de la vista 
     */
    private void limpiarCampos() {
        txtNombreEstudiante.setText("");
        txtDocumentoEstudiante.setText("");
        txtNumeroDecurso.setText("");
        txtEdadEstudiante.setText("");
        txtNombreAcudiente.setText("");
        txtNumeroAcudiente.setText("");

    }

    private boolean validarCamposBuscarYEliminar() {
        String documento = txtDocumentoEstudiante.getText();
        if (documento.isBlank()) {
            return true;
        } else {
            return false;
        }

    }

}
